const toArray = (value) => (Array.isArray(value) ? value : [])

function extractCategorySelections(entry) {
  if (!entry) return []
  if (Array.isArray(entry.categories) && entry.categories.length > 0) {
    return entry.categories
  }
  if (entry.categoryId) {
    return [{
      categoryId: entry.categoryId,
      categoryName: entry.categoryName || '',
      services: entry.services || []
    }]
  }
  return []
}

function formatItemName({ categoryName, serviceLabel, fieldLabel }) {
  const parts = []
  if (fieldLabel) parts.push(fieldLabel)
  if (categoryName) parts.push(categoryName)
  if (serviceLabel) parts.push(serviceLabel)
  return parts.join(' • ') || serviceLabel || 'Service'
}

function collectServiceItems(form, submissionData = {}) {
  if (!form?.fields) return []
  const items = []

  form.fields
    .filter(field => field.type === 'service-category')
    .forEach(field => {
      const entry = submissionData[field.id]
      if (!entry) {
        console.log(`[InvoiceGenerator] No entry found for field ${field.id}`)
        return
      }
      
      const categories = extractCategorySelections(entry)
      if (categories.length === 0) {
        console.log(`[InvoiceGenerator] No categories found in entry for field ${field.id}`)
        return
      }
      
      categories.forEach(category => {
        const services = toArray(category.services)
        if (services.length === 0) {
          console.log(`[InvoiceGenerator] No services found in category ${category.categoryName}`)
          return
        }
        
        services.forEach(service => {
          // Extract price - handle various formats: rate, price, or default to 0
          let price = 0
          if (service.rate !== undefined && service.rate !== null && service.rate !== '') {
            price = Number(service.rate) || 0
          } else if (service.price !== undefined && service.price !== null && service.price !== '') {
            price = Number(service.price) || 0
          }
          
          const quantity = service.quantity === '' || service.quantity === undefined || service.quantity === null ? 1 : Number(service.quantity) || 1
          const serviceLabel = service.customLabel || service.serviceLabel || service.serviceId || 'Service'
          
          console.log(`[InvoiceGenerator] Service item:`, {
            serviceLabel,
            rate: service.rate,
            price: service.price,
            extractedPrice: price,
            quantity,
            categoryName: category.categoryName
          })
          
          // Always add item, even if price is 0 (user can edit later)
          items.push({
            name: formatItemName({
              categoryName: category.categoryName,
              serviceLabel,
              fieldLabel: field.label
            }),
            description: field.description || '', // Empty description - user can add if needed
            quantity,
            price
          })
        })
      })
    })

  console.log(`[InvoiceGenerator] Collected ${items.length} items from submission`)
  return items
}

function buildInvoiceFromSubmission(form, submission, customer) {
  if (!form?.userId || !submission) return null
  const items = collectServiceItems(form, submission.data || {})
  if (!items.length) return null

  const subtotal = items.reduce((sum, item) => sum + (item.quantity * item.price), 0)
  const tax = 0 // No automatic tax - user can add manually if needed
  const total = subtotal // Total equals subtotal (no tax added automatically)
  const invoiceId = submission.invoiceId || `${Date.now().toString()}${Math.random().toString(36).slice(2, 8)}`

  // Include customer details directly in invoice for easier access
  const invoice = {
    id: invoiceId,
    userId: form.userId,
    customerId: customer?.id || submission.customerId || null,
    // Store customer details directly in invoice
    customerName: customer?.name || null,
    customerEmail: customer?.email || null,
    customerPhone: customer?.phone || null,
    invoiceNumber: `INV-${Date.now()}`,
    items,
    subtotal,
    tax,
    total,
    balanceDue: total, // Initialize balance due to total
    notes: '', // Empty notes - user can add notes if needed
    dueDate: null,
    status: 'sent', // Auto-generated invoices are marked as 'sent' by default
    quickbooksId: null,
    quickbooksSyncAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    formId: form.id,
    submissionId: submission.id,
    autoGenerated: true
  }

  console.log('[InvoiceGenerator] Created invoice:', {
    invoiceId: invoice.id,
    invoiceNumber: invoice.invoiceNumber,
    customerId: invoice.customerId,
    customerName: invoice.customerName,
    customerEmail: invoice.customerEmail,
    itemsCount: items.length,
    total: invoice.total
  })

  return invoice
}

module.exports = {
  buildInvoiceFromSubmission
}

